### PR TITLE
Ce dev refactor pr 1.x

### PR DESCRIPTION
**Pull request by gregharvey**

### CODE REVIEW

**Comment by gregharvey** [comment]
Added a `webserver` build to testing, as it's more realistic than `blank` as a true test of whether we broke something or not.

**Comment by gregharvey** [comment]
So now CI:
* builds its controller
* builds a web server using the meta role
* builds a clean gitlab server

**Comment by gregharvey** [comment]
Backing out of this for a moment as we need to run a ce-dev release so the main controller container has the necessary Galaxy roles available.

**Comment by gregharvey** [comment]
Catch-22 issue, CI cannot succeed on this particular PR ... HOWEVER, I can prove it will succeed it you look at this output from another build using this code in devel:

* https://github.com/codeenigma/ce-provision/runs/4705511646

So this looks good for review to me.

**Review by EmlynK — APPROVED** [review]

**Pull request merged**
